apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-app-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: dev
            url: https://kubernetes.default.svc
          - cluster: prod
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-demo'
    spec:
      project: default
      source:
        repoURL: https://github.com/InverMN/k8s-argocd-app-set-quest
        targetRevision: HEAD
        path: chart
        helm:
          valueFiles:
            - ../values/{{cluster}}.yaml
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}-demo'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
