apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - --spring.profiles.active={{ .Values.spring.profile }}
        volumeMounts:
        - name: config
          mountPath: /app
        lifecycle:
          preStop:
            exec:
              command: ["wget", "-q", "-O-", "http://localhost:8080/service/shutdown"]
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
            resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "2000m"
      volumes:
      - name: config
        configMap:
          name: config-map
          items:
            - key: config.json
              path: config.json
