apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  DB_HOST: {{ .Values.database.host }}
  DB_USER: {{ .Values.database.user }}
  DB_PASSWORD: {{ .Values.database.password }}
