apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - name: port-8080
    port: 8080
    targetPort: 8080
  - name: port-8081
    port: 8081
    targetPort: 8081
  - name: port-8082
    port: 8082
    targetPort: 8082
